name: nanox
recipe: drupal10
proxy:
  appserver:
    - nanox.dev.lando
  mailhog:
    - nanox.mailhog.lndo.site
  phpmyadmin:
    - nanox.phpmyadmin.lndo.site
config:
  php: "8.1"
  via: apache:2.4
  webroot: web
  drush: false
  database: mysql:8.0
  xdebug: false
keys: true
services:
  appserver:
    ssl: true
    config:
      php: .vscode/php.ini
    overrides:
      environment:
        USE_ACLI: 0
        USE_PUSH_DB: 0
        USE_QUERY_LOG: 0
        XDEBUG_MODE:
    build_as_root:
      - if [ -f /user/.lando.utils ]; then bash /user/.lando.utils build_as_root; fi
  mailhog:
    ssl: true
    type: mailhog
    app_mount: false
    portforward: false
    hogfrom:
      - appserver
  phpmyadmin:
    ssl: true
    type: phpmyadmin
    app_mount: false
tooling:
  utils:
    service: appserver
    description: Run the Utils command
    cmd: bash /user/.lando.utils menu
  query_log:
    service: database
    description: MySQL query logs utility.
    cmd: bash /user/.lando.utils database
    user: root
events:
  post-start:
    - if [ -f /user/.lando.utils ]; then bash /user/.lando.utils post-start; fi
  pre-destroy:
    - if [ -f /user/.lando.utils ]; then bash /user/.lando.utils pre-destroy; fi
