<?php

/**
 * @file
 */

use Drupal\Core\File\FileSystemInterface;
use Drupal\eck\EckEntityInterface;
use Drupal\pokemon_api\Utils\Utility;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function pokemon_api_us_presave(EckEntityInterface $entity) {
  // Target field name.
  $target_field = 'field_pokemon_number';

  // Get pokemon number.
  if (!$entity->hasField($target_field)) {
    return;
  }
  $pokemon_number = $entity->get($target_field)->getString();
  if (!is_numeric($pokemon_number) || $pokemon_number < 1 || $pokemon_number > Utility::POKEMON_MAX_NUMBER) {
    // Invalid Pokemon number.
    return;
  }

  // Define the file-path where data is to be stored.
  $file_path = Utility::POKEMON_DIRECTORY . '/' . sprintf('%04d', $pokemon_number) . '/' . 'front_default.png';

  if (file_exists($file_path)) {
    return;
  }
  Utility::getPokemonPhotoData(Utility::getPokemonSpritesData($pokemon_number), (int) $pokemon_number);
}
